# Generated by Django 4.2.13 on 2024-07-01 04:46

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name=django.contrib.auth.models.User)),
                ('instructeur', models.CharField(max_length=40, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_id', models.CharField(max_length=50)),
                ('tutorat', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('date_start', models.DateField(auto_now=True)),
                ('date_end', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.courses', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Niveaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ressource_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('format_r', models.CharField(choices=[('fpp', 'fpp'), ('pdf', 'pdf'), ('video', 'video')], max_length=50)),
                ('ressource', models.FileField(upload_to='Media')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.lesson', verbose_name='')),
            ],
        ),
    ]
