# Generated by Django 5.0.1 on 2024-07-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('type_user', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=50)),
            ],
        ),
    ]
