# Generated by Django 4.2.13 on 2024-07-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_type_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_user',
        ),
    ]
